// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY2W5M_xQPs0Abmz14kpilsJEDdVdzETA',
    appId: '1:455101909232:web:f5272059a1cca0f8c8da35',
    messagingSenderId: '455101909232',
    projectId: 'resume-project-5f800',
    authDomain: 'resume-project-5f800.firebaseapp.com',
    storageBucket: 'resume-project-5f800.appspot.com',
    measurementId: 'G-PV9LSE1D9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAOeQiIRCwJvLopmY287SDep27kwtbGvc',
    appId: '1:455101909232:android:ab4306da8a568448c8da35',
    messagingSenderId: '455101909232',
    projectId: 'resume-project-5f800',
    storageBucket: 'resume-project-5f800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLH7UdIwo7UkqteCg4xFKdR3UsF4CqeKA',
    appId: '1:455101909232:ios:d7f2ef1fef86318ac8da35',
    messagingSenderId: '455101909232',
    projectId: 'resume-project-5f800',
    storageBucket: 'resume-project-5f800.appspot.com',
    iosBundleId: 'com.example.csvRead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLH7UdIwo7UkqteCg4xFKdR3UsF4CqeKA',
    appId: '1:455101909232:ios:b0cfd5ea6517fbdac8da35',
    messagingSenderId: '455101909232',
    projectId: 'resume-project-5f800',
    storageBucket: 'resume-project-5f800.appspot.com',
    iosBundleId: 'com.example.csvRead.RunnerTests',
  );
}
